<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="1" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="51300" started-at="2023-01-06T16:34:52Z" finished-at="2023-01-06T16:35:43Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="51300" started-at="2023-01-06T16:34:52Z" finished-at="2023-01-06T16:35:43Z">
      <class name="org.test.assertt.Sample">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:org.test.assertt.Sample@69ea3742]" name="beforeClass" is-config="true" duration-ms="9118" started-at="2023-01-06T16:34:52Z" finished-at="2023-01-06T16:35:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="test3()[pri:0, instance:org.test.assertt.Sample@69ea3742]" name="test3" duration-ms="31311" started-at="2023-01-06T16:35:01Z" finished-at="2023-01-06T16:35:32Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
verify url expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
verify url expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at org.test.assertt.Sample.test3(Sample.java:78)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:org.test.assertt.Sample@69ea3742]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2023-01-06T16:35:01Z" finished-at="2023-01-06T16:35:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:org.test.assertt.Sample@69ea3742]" name="afterMethod" is-config="true" duration-ms="0" started-at="2023-01-06T16:35:32Z" finished-at="2023-01-06T16:35:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="test2()[pri:2, instance:org.test.assertt.Sample@69ea3742]" name="test2" duration-ms="7028" started-at="2023-01-06T16:35:32Z" finished-at="2023-01-06T16:35:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:org.test.assertt.Sample@69ea3742]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2023-01-06T16:35:32Z" finished-at="2023-01-06T16:35:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:org.test.assertt.Sample@69ea3742]" name="afterClass" is-config="true" duration-ms="3757" started-at="2023-01-06T16:35:39Z" finished-at="2023-01-06T16:35:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:org.test.assertt.Sample@69ea3742]" name="afterMethod" is-config="true" duration-ms="0" started-at="2023-01-06T16:35:39Z" finished-at="2023-01-06T16:35:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- org.test.assertt.Sample -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
